### ISSUE TITLE
Camera intrinsics do not change with resolution

### ISSUE THREAD

**Issue by ruffner** [orbbec/ros_astra_camera#84]
The camera (Stereo S) intrinsics matrix that are a part of the camera info header are not being updated by the driver whenever different resolutions are selected (after reconfigure and relaunch).

This bug appears under ROS Kinetic running the most recent version of the Orbbec driver as of today (commit hash 7832c4242b987a6a3d4bc69b95beea6cd3e6f1d6).

I believe this is related to issue #50, however it is much more general and creates a problem for anyone trying to use the Stereo S at any resolution besides 640x400.

For example. When using a resolution of 640x400, the intrinsics of the header look like
```
---
header:
  seq: 81
  stamp:
    secs: 1562872724
    nsecs: 205047600
  frame_id: "depthcam_proximity_front2_depth_optical_frame"
height: 400
width: 640
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [540.9197387695312, 0.0, 318.4385070800781, 0.0, 477.4271545410156, 184.38267517089844, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [540.9197387695312, 0.0, 318.4385070800781, 0.0, 0.0, 477.4271545410156, 184.38267517089844, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 1
binning_y: 1
---
```

After reconfiguring and relaunching, the same `rostopic echo` command shows that the resolutions have changed, but the camera intrinsics have not (except for the 6th element of K):
```
--
header:
  seq: 106
  stamp:
    secs: 1562872426
    nsecs:  19165985
  frame_id: "depthcam_proximity_front2_depth_optical_frame"
height: 200
width: 320
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [540.9197387695312, 0.0, 318.9385070800781, 0.0, 477.4271545410156, 189.38267517089844, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [540.9197387695312, 0.0, 318.9385070800781, 0.0, 0.0, 477.4271545410156, 189.38267517089844, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 1
binning_y: 1
---
```

This is most easily seen in RViz, where after switching to the 320x200 resolution, the incorrect intrinsics cause the depth image to be rendered in an incorrect location in space. Using 640x400 resolution, the depth information is rendered correctly. Two images are shown below, the first is the correct depth registration when used at 640x400, the second is the same environmnent (with recognizable features), however, it is clear that the intrinsics are causing RViz to incorrectly render the depth data.

![640x400-depth-cropped](https://user-images.githubusercontent.com/1318797/61080072-3c43cc00-a3f2-11e9-831b-f15f64e853b7.png)

![320x200-depth-cropped](https://user-images.githubusercontent.com/1318797/61080079-406fe980-a3f2-11e9-8f44-0155ba269e33.png)
